misc updates.

diff --git a/man2pdf b/man2pdf
--- a/man2pdf
+++ b/man2pdf
@@ -15,9 +15,17 @@ OUTPUT_FILE=${2}
 [[ $# -lt 1 ]] && \
     { echo -e "$(basename $0) [manual] [output file]" ; exit 1 ; }
 
+# Check 'man' command.
+command -v man >/dev/null 2>&1 || \
+    { echo "command 'man' not found, exiting." ; exit 1 ; }
+
 if [[ "${OSTYPE}" == "darwin"* ]] ; then
+    command -v pstopdf >/dev/null 2>&1 || \
+        { echo "command 'pstopdf' not found, exiting." ; exit 1 ; }
     man -t "${PAGE}" | pstopdf -i -o "${OUTPUT_FILE}"
-elif [[ "${OSTYPE}" == "linux-gnu" ]] ; then
+elif [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "freebsd"* ]] ; then
+    command -v ps2pdf >/dev/null 2>&1 || \
+        { echo "command 'ps2pdf' not found, exiting." ; exit 1 ; }
     man -t "${PAGE}" | ps2pdf - > "${OUTPUT_FILE}"
 else
     echo "Not supported OS type: ${OSTYPE}"
