Revert "updates."
This reverts commit ebc7f455dd2167a3f20b38612fc372613583995f.

diff --git a/scripts/lib b/scripts/lib
--- a/scripts/lib
+++ b/scripts/lib
@@ -39,10 +39,7 @@ init_logfile () {
 # logger.
 #
 log () {
-    local str="$(date +'%D %T '): $1"
-    echo -e "$str" >> "$LOGFILE" || { echo "Log failed" ; exit 127 ; }
-    [[ $LOG_TO_STDOUT == "yes" ]] && echo -e "$str"
-
+    echo -e "$(date +'%D %T ')" >> "$LOGFILE" || { echo "Log failed" ; exit 127 ; }
 }
 
 #
